### ISSUE TITLE
Vehicle Display Name

### ISSUE THREAD

**Issue by MichaelCoppJr** [ogmudboneshmurda/noire_vehicles#1]
Vehicle affected: 
2013 Bentley Mulsanne Mulliner

Display name shown:
'BLANK', Sedans

Corrected display name:
2013 Bentley Mulsanne Mulliner, Sedans

**Comment by ogmudboneshmurda** [comment]
Fixed in 32e1d3fe11a2913e017fd853eb1a1974f9166b35.
