### ISSUE TITLE
King Ranch 6x6

### ISSUE THREAD

**Issue by DankGrandma** [ogmudboneshmurda/noire_vehicles#101]
https://youtu.be/8eUBGMcr7JY 
clip from 4/4 about 12pm pst

the king ranch 6x6 went from 400 to 250 inv space. i thought it had semi truck sounds but it has dump truck sounds
<audioNameHash>dump</audioNameHash>

the class seems to be <vehicleClass>VC_OFFROAD</vehicleClass>
but shows compact in game. the handling feels off too, im comparing it to the F350 work truck in regards to some off-roading (flips easy, spins out in sand)
im also not sure what causes the shaking/smoking when stopped (see video) but hope its fixable

**Comment by DankGrandma** [comment]
i double checked after 5pm restart

**Comment by DankGrandma** [comment]
the class seems to be <vehicleClass>VC_OFFROAD</vehicleClass>
 but i think theres supposed to be an underscore between off and road
 for the audiohash can we go with >monster< sounds

**Comment by DankGrandma** [comment]
the wheel thing may be that the king ranch has <wheelType>VWT_SPORT< wheels in the vechicles meta.
the worktruck has <wheelType>VWT_SUV<

**Comment by ogmudboneshmurda** [comment]
fixed, 6f390f6
