### ISSUE TITLE
1970 dodge challenger's torque is so bad you can barely even drive it

### ISSUE THREAD

**Issue by makka69420** [ogmudboneshmurda/noire_vehicles#106]

**Comment by DankGrandma** [comment]
raising the fTractionCurveMax, min and lateral around 2.25; 1.8 and 22.5 might help traction

**Comment by ogmudboneshmurda** [comment]
https://github.com/ogmudboneshmurda/noire_vehicles/commit/e42b903c29150e95dde3a03f526c53d8409a1961#diff-3499fb9ecbceecccff39d4bf924165a733f3b8a548f27b59707b8094adf0f173
