### ISSUE TITLE
Ferrari California T luxury auto  

### ISSUE THREAD

**Issue by veprezy** [ogmudboneshmurda/noire_vehicles#107]
the top speed is slow only got to 139 downhill when a stock one irl does 195mph and in game the Pagani is 10k more and does 190 the Ferrari definitely needs a buff

**Comment by DankGrandma** [comment]
try cutting fInitialDragCoeff value= to about 6 or 5. should help bump it up

**Comment by ogmudboneshmurda** [comment]
https://github.com/ogmudboneshmurda/noire_vehicles/commit/e42b903c29150e95dde3a03f526c53d8409a1961#diff-ae51d96cb814bf2ebe6d7b1f25af98f81e478410b601cc01d90eb46542ad492e

should be better now
