### ISSUE TITLE
Ferrari 458 Prior Luxury Autos

### ISSUE THREAD

**Issue by Ziggyyyyy** [ogmudboneshmurda/noire_vehicles#108]
Gets stuck in third gear and feel like it should be doing more than 160mph

**Comment by DankGrandma** [comment]
bringing fInitialDragCoeff value= down to about 7 or 8 should help top end a bit. the 3rd gear may be from RateScaleUpShift and RateScaleDownShift not being the same value. not for sure tho

**Comment by ogmudboneshmurda** [comment]
https://github.com/ogmudboneshmurda/noire_vehicles/commit/e42b903c29150e95dde3a03f526c53d8409a1961#diff-c8d2ee4e7822c024e1f9cd863839bedb8f33a4c827b5732675024d0ecd3523c1
