### ISSUE TITLE
Buff audi r8 acceleration

### ISSUE THREAD

**Issue by Ahy-jason-todd** [ogmudboneshmurda/noire_vehicles#109]
acceleration just isnt great for a 400k car on top of the fact I cant upgrade anything on it so if possible slight buff would mean a lot and would be great also since its no upgradable at all can you bull the base health a little bit

**Comment by DankGrandma** [comment]
bumping fInitialDriveForce value= to about 0.55 might help. 
carcols.meta shows all the upgrades so I'm not sure there, unless there's some code typo

**Comment by ogmudboneshmurda** [comment]
e42b903c29150e95dde3a03f526c53d8409a1961

**Comment by Ahy-jason-todd** [comment]
so did it get buffed?

**Comment by ogmudboneshmurda** [comment]
> 
> 
> so did it get buffed?

https://github.com/ogmudboneshmurda/noire_vehicles/commit/e42b903c29150e95dde3a03f526c53d8409a1961#diff-1883fb6b84505729bfc30fe6cb49d8f42555867d4eaf0167c0fcdc455593797a

yes, increased the shift rate and drive inertia, should have better acceleration now
