### ISSUE TITLE
Dodge Demon too weak

### ISSUE THREAD

**Issue by Yush6969** [ogmudboneshmurda/noire_vehicles#11]
Dodge Demon is a weak car imo, I got rear ended the other day not very hard and it instantly broke down. When in a police chase i pushed the police vehicle with the car at a low speed and it then broke down.

**Comment by ogmudboneshmurda** [comment]
fixed in 75eea83997a93fbcf64c59397f35bdb955266f92

**Comment by yomking18Twitch** [comment]
Hi my name is Benjamin Santiago and l want to be a Police officer
