### ISSUE TITLE
Shelby GT500

### ISSUE THREAD

**Issue by Sosa420** [ogmudboneshmurda/noire_vehicles#110]
needs to fix the suspension,really fucking bouncy, doesnt turn, so many problems plus all of that needs a serious rework

**Comment by DankGrandma** [comment]
only thing far out of norms i can see is fRollCentreHeightFront value=1.43.. other similar stuff has about 0.142

and also fSuspensionCompDamp value= 2.215, where around 1.8 is what other similar stuff has

**Comment by ogmudboneshmurda** [comment]
> 
> 
> only thing far out of norms i can see is fRollCentreHeightFront value=1.43.. other similar stuff has about 0.142
> 
> and also fSuspensionCompDamp value= 2.215, where around 1.8 is what other similar stuff has

yep, was the suspension the whole time. finally fixed! e42b903
