### ISSUE TITLE
Lamborghini Huracan Performante (Luxury Autos)

### ISSUE THREAD

**Issue by MontFu** [ogmudboneshmurda/noire_vehicles#111]
The car tops out at 114 fully upgraded. Raced against the same car at the other dealership, he was pushing 190-200

**Comment by DankGrandma** [comment]
fInitialDragCoeff value is 7.6 on the hurper (huracan performance) and 4.1 on the PDM huracan (pdm)

fInitialDriveMaxFlatVel value is 152 on hurper and 225 on huracan. might need to be the same or however you see fit

**Comment by ogmudboneshmurda** [comment]
set the hurper's handling to be identical to the hevo
https://github.com/ogmudboneshmurda/noire_vehicles/commit/e42b903c29150e95dde3a03f526c53d8409a1961#diff-ce3a0206586f7b3f511543135e258616c2ddbad81ee619c51d007b5da1157a91
