### ISSUE TITLE
Mercedes-Benz G65 AMG Trunk space

### ISSUE THREAD

**Issue by Frostwhale22** [ogmudboneshmurda/noire_vehicles#114]
I don't know if this was purposely but the trunk space on the the Amg truck is is 750 I understand If this was purposely because of some other reason.

**Comment by ogmudboneshmurda** [comment]
intentional, trunk space is vehicleClass dependent: https://github.com/ogmudboneshmurda/noire_vehicles/blob/e42b903c29150e95dde3a03f526c53d8409a1961/DATA/g65amg/vehicles.meta#L98
