### ISSUE TITLE
Maserati Levante

### ISSUE THREAD

**Issue by degzy1** [ogmudboneshmurda/noire_vehicles#116]
in my opinion this car needs an acceleration buff an top speed buff please as definitely faster irl

**Comment by ogmudboneshmurda** [comment]
https://github.com/ogmudboneshmurda/noire_vehicles/commit/7fd4684c427453906f25ff97141f7c0520e9de3f#diff-bdff5b531e033b78bb42dde7f6e65f752c049cdaa044be1fd27645021d9ad616
