### ISSUE TITLE
Nissan Skyline GTR

### ISSUE THREAD

**Issue by Jxstinn** [ogmudboneshmurda/noire_vehicles#117]
Nissan Skyline needs a major buff. The 0-60 is terrible and the top speed is like 120 when in reality a skylines top speed can go up to almost 200 but 175 on average. Car definitely needs upgrades added to it as well (armor etc) as they aren't available at the customs shop. To clarify, its the $70k Skyline at the supporter dealership.

**Comment by ogmudboneshmurda** [comment]
https://github.com/ogmudboneshmurda/noire_vehicles/commit/7fd4684c427453906f25ff97141f7c0520e9de3f#diff-65d1b39534b185e21ee9c9d32b2d85ac6081e9af3ecdccc5e71c887e46bfc899
