### ISSUE TITLE
Maserati Levante Novitec

### ISSUE THREAD

**Issue by LactatingWalrus** [ogmudboneshmurda/noire_vehicles#118]
I think this car could use a slight visual rework when it comes to the tail lights. They look a bit wonky. Also, the top speed should be around 185 according to google.

**Comment by ogmudboneshmurda** [comment]
https://github.com/ogmudboneshmurda/noire_vehicles/commit/7fd4684c427453906f25ff97141f7c0520e9de3f#diff-bdff5b531e033b78bb42dde7f6e65f752c049cdaa044be1fd27645021d9ad616
