### ISSUE TITLE
PDM Vehicle Addition

### ISSUE THREAD

**Issue by MichaelCoppJr** [ogmudboneshmurda/noire_vehicles#16]
Vehicle Addition Requested by: @OGXX 

https://www.gta5-mods.com/vehicles/chevrolet-caprice-1989

1989 Chevrolet Caprice, Sedans

**Comment by BaguetteRP** [comment]
Vehicle Request is the Mazda Rx7 I would want this vehicle to be added because it is a nice affordable sports car. And it has a lot of customizability. 

[https://www.gta5-mods.com/vehicles/mazda-rx7-fd3s-add-on-tunable](https://www.gta5-mods.com/vehicles/mazda-rx7-fd3s-add-on-tunable)
