### ISSUE TITLE
2016 Porsche 911 Turbo S Problems

### ISSUE THREAD

**Issue by TheFamousX2** [ogmudboneshmurda/noire_vehicles#19]
![Screenshot (118)](https://user-images.githubusercontent.com/73058919/106442728-eaeba980-647b-11eb-9f69-179d945b264a.png)
![Screenshot (116)](https://user-images.githubusercontent.com/73058919/106442816-06ef4b00-647c-11eb-8fcb-74a15f6e2186.png)

As you can see in two screenshots I uploaded Porsche has some problems.  In the first screenshot the problem is that tail lights are not shown to work when the car is covered in dust. In the second screenshot you can see the hood of a car opens up after the repair and there is no way to close it.

Also as Michael stated earlier Porsche should be AWD car but in the game its FWD.
Some minor health buffs are needed to, I know its a sports car and should be fragile, but cracked windshield or door scratch shouldnt make car start smoking.

**Comment by ogmudboneshmurda** [comment]
added health improvements in c365ebb
