### ISSUE TITLE
PDM Backroom Vehicle Price Update

### ISSUE THREAD

**Issue by MichaelCoppJr** [ogmudboneshmurda/noire_vehicles#21]
Effect Vehicle: 2020 Ferrari F8 Tributo

Current Price: $1,287,500

Relative IRL Price: 
$300,000 - $500,000

IRL this vehicle brand new MSRP is from $276,550.

**Comment by ogmudboneshmurda** [comment]
300-500k might be too low considering trucker pays 24k/hr, which implies someone can grind for 20 hours straight and get a supercar.. Need to do balancing on supercar prices in the back.
