### ISSUE TITLE
PDM Vehicle Update

### ISSUE THREAD

**Issue by MichaelCoppJr** [ogmudboneshmurda/noire_vehicles#22]
Effect Vehicle: 2019 BMW M8

name/category change

Current: 2019 BMW M8, Super

Updated: 2019 BMW M8, Sports

BMW is not a super car brand, the M8 realistically is not a super car. 

Additionally I think the acceleration should be slightly quicker, for such a big engine it's a bit slow to get up to speed.

**Comment by ogmudboneshmurda** [comment]
fixed in c7bd54a
