### ISSUE TITLE
Mustang Boss 429 - Speed(s)

### ISSUE THREAD

**Issue by Darkplayer38** [ogmudboneshmurda/noire_vehicles#31]
Mustang Boss 429 speeds are inaccurate, I've done some testing in-game to capture their current speeds against real-world tests below,

In-game Speeds (With Turbo):
Top Speed: 105MPH (Downhill)
0-60: 7.2-7.5 Seconds
0-100: 27.3 - 31.5 Seconds

Realistic Speeds:
Top Speed (stock): 128MPH
0-60: 6.8s
0-100: 13.8

With a turbo realistically you should see speed increases from stock of 15-20%

**Comment by ogmudboneshmurda** [comment]
should be improved in 30ba2c0
