### ISSUE TITLE
Tesla roadster 

### ISSUE THREAD

**Issue by natestwrt** [ogmudboneshmurda/noire_vehicles#32]
Is it possible for the roadster to go as fast as it does in real life or some what close to real stats

https://www.tesla.com/roadster
Heres a link for reference

**Comment by ogmudboneshmurda** [comment]
Here are the real life specs:

Acceleration 0-60 mph
1.9 sec
Acceleration 0-100 mph
4.2 sec
Acceleration 1/4 mile
8.8 sec
Top Speed
Over 250 mph

I find it unlikely that these specs are actually true, especially for an electric car. For all RP purposes, having a vehicle that can go 250MPH+ would be wildly unbalanced and extremely unrealistic.
