### ISSUE TITLE
Z/28 Speed 

### ISSUE THREAD

**Issue by DefendedGamer** [ogmudboneshmurda/noire_vehicles#33]
The Z/28 speed is broken stock it was able to hit 150 in irl it hits 180 but I fully maxed it out and it still is only going 150

**Comment by ogmudboneshmurda** [comment]
Vehicles usually have an electronic speed limiter or governor to cap max speed at ~155MPH.

For the price, the Z28 Camaro shouldn't be able to go 180MPH.
