### ISSUE TITLE
Dodge 1500

### ISSUE THREAD

**Issue by MrInsomnia32** [ogmudboneshmurda/noire_vehicles#35]
Dodge 1500 is in wrong class. trunk size is 250. suppose to be 1000 like other trucks its size.

**Comment by ogmudboneshmurda** [comment]
This has been a known issue for a while, even though the class is clearly correct in the vehicles.meta
https://github.com/ogmudboneshmurda/noire_vehicles/blob/fdeacaf6b78155d5dd8750cd62b4b8c3a2dbed63/DATA/ram1500/vehicles.meta#L88

**Comment by ogmudboneshmurda** [comment]
ram1500 has been removed
