### ISSUE TITLE
2017 Chevy Colorado Vehichle health/armor

### ISSUE THREAD

**Issue by EatSukSukFace** [ogmudboneshmurda/noire_vehicles#40]
The Colorado seems to be having issues with breaking randomly, sometimes right after using a repair kit on it. At times the repair even has no effect on the vehicle health, other times it fully repairs. When it does repair, sometimes it lasts great, other times it just breaks even though I have not hit anything since repairing.

**Comment by ogmudboneshmurda** [comment]
This shouldn't be a problem, damage values seem fairly reasonable: https://github.com/ogmudboneshmurda/noire_vehicles/blob/fdeacaf6b78155d5dd8750cd62b4b8c3a2dbed63/DATA/checol17/handling.meta#L42
https://github.com/ogmudboneshmurda/noire_vehicles/blob/fdeacaf6b78155d5dd8750cd62b4b8c3a2dbed63/DATA/checol17/handling.meta#L43
https://github.com/ogmudboneshmurda/noire_vehicles/blob/fdeacaf6b78155d5dd8750cd62b4b8c3a2dbed63/DATA/checol17/handling.meta#L44
https://github.com/ogmudboneshmurda/noire_vehicles/blob/fdeacaf6b78155d5dd8750cd62b4b8c3a2dbed63/DATA/checol17/handling.meta#L45
