### ISSUE TITLE
BMW M4 F82 Needs More Power

### ISSUE THREAD

**Issue by zaidiot** [ogmudboneshmurda/noire_vehicles#43]
The car dose 120MPH The car i had before costs less and its faster so pliz boost it up bit my car before did 145MPH.

**Comment by zaidiot** [comment]
The Car goes 155 stock in real life wtih upgrades it should go 175 to 180Mph should the top speed be.

**Comment by ogmudboneshmurda** [comment]
fixed in 7cec250
