### ISSUE TITLE
2017 Koenigsegg Agera RS Handling and Sounds

### ISSUE THREAD

**Issue by phxsec** [ogmudboneshmurda/noire_vehicles#48]
the braking for this vehicle is a bit unorthodox
the acceleration for the vehicle isn't the greatest either - top speed is 130 and takes about 10 secs to at least get from 100-130

https://www.gta5-mods.com/vehicles/2017-koenigsegg-agera-rs-handling-and-sounds

**Comment by ogmudboneshmurda** [comment]
61d402b
