### ISSUE TITLE
Kia stinger 2017

### ISSUE THREAD

**Issue by Peskyy** [ogmudboneshmurda/noire_vehicles#53]
It burns around 1 fuel every 30 seconds. I also think that it should be a bit more faster since stock gt goes around 167 mph, when the fully maxed out stinger in the server goes around 156. I think you should make stock version also a bit faster and maxed too because stock goes like 120 not even. Maybe make stock go 148 and make maxed go 180-190

**Comment by ogmudboneshmurda** [comment]
fixed in 752432128138e5b287d990eaed3b165e5b740fc6
