### ISSUE TITLE
Gl63 in luxury autos needs fixing 

### ISSUE THREAD

**Issue by degzy1** [ogmudboneshmurda/noire_vehicles#54]
Everythink excepte the cars strength is good. But as soons you touch somthink or somone vdms you because they love gta driving an lack any sort of rp my car is totally finished just needs strength after all its a big suv an there very strong irl please let me know this shit also cost me 130+k an cant even flex it

**Comment by ogmudboneshmurda** [comment]
fixed in 7cec250
