### ISSUE TITLE
Venom GT

### ISSUE THREAD

**Issue by DefendedGamer** [ogmudboneshmurda/noire_vehicles#59]
I like the car and all don't get me wrong but the car is 350K and the top speed is 150-165 you cant turn when you do the back end likes to slide out. Top speed of the car IRL is 265 I know you wouldn't put it that high but at least 200-215 but a 100K dodge charger hellcat can hit 205 flat and 215-220 downhill. it just don't make since

**Comment by DefendedGamer** [comment]
https://youtu.be/UVz425arWRM

**Comment by DefendedGamer** [comment]
don't forget the curb boosting from the suspension being to low

**Comment by ogmudboneshmurda** [comment]
fixed in 752432128138e5b287d990eaed3b165e5b740fc6
