### ISSUE TITLE
Stuck in last gear in high speeds

### ISSUE THREAD

**Issue by rawranevilpanda** [ogmudboneshmurda/noire_vehicles#62]
If you fully upgrade the dodge demon or Chevy c8 corvette and take it past 165 it stays in the highest gear until you go in reverse or come to a complete stop for a couple of seconds, there could be other cars affected but those two I know of for sure do it.

**Comment by ogmudboneshmurda** [comment]
reverting the 'sundayDriver' option should fix this tomorrow
