### ISSUE TITLE
BMW m8 buff 

### ISSUE THREAD

**Issue by Ahy-jason-todd** [ogmudboneshmurda/noire_vehicles#65]
Hey can we a buff on Bmw m8 its 190k car that struggles to after like 110. Transmission for whatever reason caps at lvl 3 in the los santos maybe fix it to at least 4 and make the car a bit faster realistically the car should have no problem going at least 140-150 and then start struggling to climb higher.

**Comment by SAMOXID** [comment]
I agree, it does need to be faster for the price.

**Comment by ogmudboneshmurda** [comment]
fixed 8f0f167
