### ISSUE TITLE
Tesla roadster buff 

### ISSUE THREAD

**Issue by Ahy-jason-todd** [ogmudboneshmurda/noire_vehicles#66]
Hey can we a buff on tesla roadster car has no problem reaching like 115 however for a 200k car and a supporter vehicle I think it shouldn't be capped speed around 130-140 and that's being a little generous. Speed should cap around 160-170 considering its a 250mph car IRL. Also look into teslas upgrades from los santos not saving

**Comment by ogmudboneshmurda** [comment]
fixed 8f0f167
