### ISSUE TITLE
Subaru brz rocket bunny health 

### ISSUE THREAD

**Issue by m249GoBrrt** [ogmudboneshmurda/noire_vehicles#67]
The brz recently added is extremely weak, I hit two stop signs on accident and it was already smoking

**Comment by ogmudboneshmurda** [comment]
https://github.com/ogmudboneshmurda/noire_vehicles/blob/196320e8c0b00b50de7b0aaf4830dea3e886b927/DATA/brz_data/handling.meta#L41
https://github.com/ogmudboneshmurda/noire_vehicles/blob/196320e8c0b00b50de7b0aaf4830dea3e886b927/DATA/brz_data/handling.meta#L42
https://github.com/ogmudboneshmurda/noire_vehicles/blob/196320e8c0b00b50de7b0aaf4830dea3e886b927/DATA/brz_data/handling.meta#L43
https://github.com/ogmudboneshmurda/noire_vehicles/blob/196320e8c0b00b50de7b0aaf4830dea3e886b927/DATA/brz_data/handling.meta#L44
damage values seem fine to me, should be ok with armor upgrades

**Comment by m249GoBrrt** [comment]
Alright awesome thank you
