### ISSUE TITLE
RX7 issue

### ISSUE THREAD

**Issue by BlizzWizz** [ogmudboneshmurda/noire_vehicles#68]
The RX7 needs both better speed and better handeling. The car cost's 125k and dont go over 100 almoste. Also you need to plan the turn 10 seconds before it comes.

**Comment by BlizzWizz** [comment]
https://github.com/ogmudboneshmurda/noire_vehicles/tree/master/DATA/mazdarx7_data Just to make it faster to finde :)

**Comment by ogmudboneshmurda** [comment]
> 
> 
> https://github.com/ogmudboneshmurda/noire_vehicles/tree/master/DATA/mazdarx7_data Just to make it faster to finde :)

wrong one

https://github.com/ogmudboneshmurda/noire_vehicles/blob/196320e8c0b00b50de7b0aaf4830dea3e886b927/DATA/fd_data/handling.meta

fixed in a3b59c9
