### ISSUE TITLE
Dodge Demon PDM

### ISSUE THREAD

**Issue by ImDead48** [ogmudboneshmurda/noire_vehicles#83]
Love the Demon just wondering why it's classed as a compact rather then muscle?

**Comment by DankGrandma** [comment]
VC_IMUSCLE

just a typo in the vehicles.meta

**Comment by ogmudboneshmurda** [comment]
fixed, along with 2 others
https://github.com/ogmudboneshmurda/noire_vehicles/commit/e42b903c29150e95dde3a03f526c53d8409a1961#diff-9e83add1d30ce38b61cd4bc556e30bd76451fb0b6d3e8116098a5b853d79a676
