### ISSUE TITLE
2020 Srt Dodge Charger Hellcat

### ISSUE THREAD

**Issue by Frostwhale22** [ogmudboneshmurda/noire_vehicles#89]
The Dodge Charger hellcat 2020 breaks down very fast I thought it was only me I asked other people and they had the same problem I just wanted to know if y’all could look in to it.

**Comment by Frostwhale22** [comment]
The hellcat also sounds very loud can y’all turn it down

**Comment by DankGrandma** [comment]
the health and damage mults all look standard..

not sure why the sound is so loud.. its using the audioNameHash hotknife.. maybe use audioNameHash MAMBA

**Comment by ogmudboneshmurda** [comment]
looking for a supercharger whine sound, will update it when I find one
