### ISSUE TITLE
c6 corvette and jeep wrangler?

### ISSUE THREAD

**Issue by calebaustin8** [ogmudboneshmurda/noire_vehicles#9]
https://www.gta5-mods.com/vehicles/chevrolet-corvette-c6-z06-2006-add-on

https://www.gta5-mods.com/vehicles/jeep-wrangler-unlimited-jk-2013-add-on-tuning

**Comment by ogmudboneshmurda** [comment]
added in 75eea83997a93fbcf64c59397f35bdb955266f92 and 32e1d3fe11a2913e017fd853eb1a1974f9166b35
