### ISSUE TITLE
2020 Corvette C8 

### ISSUE THREAD

**Issue by Sosa420** [ogmudboneshmurda/noire_vehicles#90]
the acceleration is horrible and the sound is disgusting it sounds terrible

**Comment by DankGrandma** [comment]
could switch audioNameHash from COQUETTE to TYRUS or CHEETAH

the shifting speeds look good, raising fInitialDriveForce value  up to 0.4 might help acceleration

**Comment by ogmudboneshmurda** [comment]
changed audiohash
https://github.com/ogmudboneshmurda/noire_vehicles/commit/e42b903c29150e95dde3a03f526c53d8409a1961#diff-3d0494c23b4dac0f6e14781b44479776c8703735a4821d786b882828ebce5a3b
