### ISSUE TITLE
King Ranch Ford 6x6

### ISSUE THREAD

**Issue by B-Rad4** [ogmudboneshmurda/noire_vehicles#97]
Its a 6x6 ford, costs 150k out of supporter shop but only has 400 storage, and the regular 52k ford raptor along with most trucks have 1000. I think for the large price tag, how large the truck is, etc. it should come with 1000 storage.

**Comment by DankGrandma** [comment]
it also has the sounds like it has a trailer attached, sounds like something keeps banging around when you drive. idk, i just crank up Rebel Radio

**Comment by DankGrandma** [comment]
yup all the sounds seem to be from a semi (braking sounds, crash sounds) the F350 work truck (same mod maker i think) has good truck sounds if its a swapable thing

**Comment by ogmudboneshmurda** [comment]
fixed 1e57417
